name: ez
summary: EZ
description: |
  nope
version: '2.2.dev'
grade: stable
confinement: strict

base: core20


apps:
  go:
    command: bin/wtf

parts:
  launchers:
    plugin: dump
    source: bin/
    organize:
      '*': bin/
